image: docker:latest

services:
  - docker:dind

stages:
  - build
  - deploy

build-image:
  stage: build
  script:
    - docker build -t "$CI_DOCKER_USER/$CI_DOCKER_IMAGE" .
  except:
    - tags

deploy-image-tag:
  stage: deploy
  before_script:
    - docker login -u "$CI_DOCKER_USER" -p "$CI_DOCKER_PASSWORD" $CI_REGISTRY
  script:
    - docker build -t "$CI_DOCKER_USER/$CI_DOCKER_IMAGE:$CI_COMMIT_TAG" -t "$CI_DOCKER_USER/$CI_DOCKER_IMAGE:latest" .
    - docker push "$CI_REGISTRY/$CI_DOCKER_USER/$CI_DOCKER_IMAGE:$CI_COMMIT_TAG"
    - docker push "$CI_REGISTRY/$CI_DOCKER_USER/$CI_DOCKER_IMAGE:latest"
  only:
    - tags
